### ISSUE TITLE
Android notifier error

### ISSUE THREAD

**Issue by trentyarwood** [BobVul/GrowlToToast#22]
GtT 2.0
Windows 10 Pro v 1803
Growl 2.0.9.1
MultiDroid notifier 0.51_x64 -  https://code.google.com/archive/p/android-notifier/downloads\
Windows Java v 1.8.0_171

Android P preview on Google Pixel
Remote notifier 0.2.8

PC > Growl > Display > GTT > Preview > works as expected
Android > Remote notifier > Send test notification > works as expected when display set to (notGTT)

Android > Remote notifier > Send test > Error (see screen dump below, but no log file created at the file location in the first line)

![untitled](https://user-images.githubusercontent.com/10393897/41276395-757f3e76-6e67-11e8-81fc-bbbc251ca249.png)

**Comment by BobVul** [comment]
Please install v2.0.1 from https://github.com/BobVul/GrowlToToast/releases/tag/v2.0.1

I've updated the logging to provide more information (and actually write the file!). You can find the logs under `%LocalAppData%\GrowlToToast\`.

If you could provide those logs, that'd be great. I have a vague idea how to fix this (either strip out or encode any random null characters) but I'd like to know which field they're appearing in.

**Comment by BobVul** [comment]
Oh, you'll also need to enable debug logging via the Growl settings panel (new checkbox). That will provide far more detail than just the error logging.

**Comment by trentyarwood** [comment]
```
2018-06-13 15:59:45.119 +10:00 [DBG] Received "{"Action":1,"Title":"Trent Pixel sent a ping","Body":"Test notification\u0000","Silent":false,"Image":"iVBORw0KGgoAAAANSUhEUgAAAEgAAABICAYAAABV7bNHAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAd9SURBVHhe7ZltUFRVGMftQ/mhPjVN2Uwz1dQHhppmasqSVCwVEFB53WXZN2CXXRZ2QWCB3WWX3UVaFMFcWVhgYRUEX8rIUZCUUilN8y2zlylrptK0fLnUZNqm4tNzLremxtuL7Lk1K/c/8x+Ge85zLs/v3POcey5TRIkSJUqUKFGiRIkSJUqUKFG3qja/deTBTUOHinsHDtb2bD0QsV4/eMi9aftBxY5jx+7kUgtfjT1vxNS1DZ62eLdCWWN/ZLupH+wtA7CsY2iksW/3PVyKE5dO1357iWfjPkPdRsipXgO59sg3yaOkoR9M9RtruTQnLkX5insVliCjda4DTU33LWNd7XpQWjuHuDQnrszChmkKSxejdQkLiIyf5+jG2Q1CXk0PCD0hBJC8qu0NLs2J6z8BhDCyjB6Q5RohR2cCidoIinKvoJAIIJUlQAtQkNG5eyHf2UPfrl5QlTVBdbUddu96E45/cAy29G8GfXElaBxr+WMouGDphsgApMXlZKpaCkcOH4Lr168D0aVLl6AriEvN0oJ91t0QQ8MRA4g8JfVNPjh37iwLh4iAGt65A/S21ewy44sL1xEFaKUvAKPMBQ7PuPbt2wtGhy8yACkRkL62D3RYqGlbiwWzqbkTmAvnOTTj2r//XSh2trI1ii8uXJP3OnVEPEEIaLm3A86d/Y5DM659e98BEwISnyAEUNfUDmdOf8OhGa9Bu3btAqOzXXyCNDXrwNnQBl9/9SWHB+DatWswuH07GGoCYpEmAGz1fvji8884PABXrlyBza+9DvqaTmznjwvXEQWosq4VPvn4Qw4PwM8/X4aevk2Q7wjyxtAwZUBdggIqq22F948e4fAAXLz4I7QHsT451vDG0HBEASpx+eG9A/s5PADfjzLg9a/BV4CIOWp0MflY+ck7C21r8KhR5PTD2yMjHB7ALf9bWOYNsKd7vhga1pPDKr3TfKdgp3nyaaPA0QbDw8O4vY+xgE6d/BrcK9ogFwHxxdAw5c8dnYwGH8s8PBbQNoGgs7fDtoFBdnsn+uLzE2Dz+CEH2/hiaDjf3RcpgNaCtrqD3davXr3CAvr4o+NgXtoaSYBaGbIUcu2YkADOswWgd/0rEAqFWECHDx1kz2E59m7e/jSsdSEgMy1AVS0MWQrkY7cgtnVBB27rP/10kQU0smcPGBx+UFev5e9PwRpnLwLyRwYgNXq5t5M9sJI69Fr/FtDaA+x1vv40TBdQpY8hg6pxpoWwyhaEsroADO/cCUePHIZ6bxCTCOJ1/v40TEpGtrmFDiB5hY9RYxIqa6cgVlo6QYNvzbbGXnCu6gNDbTdvP5omKyK73EcJkBkBWXGmLQFBTe5BZpevjbZJoZaWe2kAck5D0owKZ1lZ1SGs8Q8nTxP7k6+doknJkJZSAJSIgGRlzQwZVFHZJoyr2iG7wg/pBg+k6WpBWvIyXhPwfmjypEqXrKIASO2clmVczZBB5RWtAtgPWaWrQZJjgsrKKnC7XaAtMEKG3olteE8zX0z4VlkDkGFqogNIWrSKwS0Ri1oLfeO4cr0V+tZ1w5kzp2F0dJT99FFltYPUtIIFxBsXpsmKoAZIUvgyQwbFpUbd0iVesLmWwalTJ9mXRKKxsTEYHNgGyuI6yCoT5r5kRWQYG2gBWsnIynzsUqBtAsjT6IPzf/jHIdHInt2gMTdgIeWPC9dkaVMDtLiwniGDYlGjbgkCKnf72A9mv/wSwqfnGlw4fxaCPRtAZfZiO39cuMaXRNwUltMBtKjQw0hLMJnildSdiVaam8G9cg30bx2CHW/uhkDPq2B0toEEdzO+GBqW4YSnGDw0AJmnLTJ4GDJopqlRMMtwVjXWFtBV4w5T0Yzgmnj70XIW3i9F91L4gF7MKr4vJc81mmlqwjW7QjCnFzX8yXx9aJq8ay3SundwaU5cCQmmqXFKy3FCPb1w+U16GaQZbs7849B3prER4rLLV3FphqeZyboUhHQ5DRMmSf9bpxZ4bspphnqMIwnwj0fL5F7zJaUnno1XP8SlGL5i4pUz5qQamuekGTb8o1ML1r+QXjSQoLKNpehfwrVe948mf3SSuhowbojE845Lwzh27GK9a3qC/AEutf9H8zOMDycrHaEU3VJYnF/7tyaAFigt159P0li58FtfcbKyqCSFPYSFEBZqXH9pAiguu+TqjAXqIi50cig2zRiVKLeFFubVQHKu40bjdQJoXpbxckyCSsGFTR4RQAvklhCBkZRjv8EE0OxM0w/T47MXcyGTSwTQi/KKUKLaBgtU1j85MacaYtMKzz4zTzqX6z75FJumi3pBVh7C4gsJiqrfTX6fnZJ/8qk56c9yXSenCKBYaWkoXl6BRdgM8dkVEC+vhJlJmk+fiE19nOs2eTUjWRc1W1ISipOVw2+OSVQffSwm4RGuy+TWjGR11KwMfWh+VinMky6B5+Lk70TNir+faxbFAkrXheZmFsP0+bKh6Ofi7uaaRBGRJTZroQaenit5NTo69i7usqjf9HSs5PEnZ6W2PvpowlTukqg/Kjo68w78cdv4b6JEiRIl6uY1ZcqvkiXTI7HnmxIAAAAASUVORK5CYII=","AppName":"Android Notifier","PersistNotifications":false}"
2018-06-13 15:59:45.271 +10:00 [DBG] Deserialized {"Action":"Show","Title":"Trent Pixel sent a ping","Body":"Test notification\u0000","Silent":false,"Image":{"Tag":null,"PhysicalDimension":{"IsEmpty":false,"Width":72,"Height":72,"$type":"SizeF"},"Size":{"IsEmpty":false,"Width":72,"Height":72,"$type":"Size"},"Width":72,"Height":72,"HorizontalResolution":95.9866,"VerticalResolution":95.9866,"Flags":77842,"RawFormat":{"Guid":"b96b3caf-0728-11d3-9d7b-0000f81ef32e","$type":"ImageFormat"},"PixelFormat":"Format32bppArgb","Palette":{"Flags":1908806280,"Entries":[],"$type":"ColorPalette"},"FrameDimensionsList":["7462dc86-6180-4c7e-8e3f-ee7333a7a483"],"PropertyIdList":[771,769,20752,20753,20754],"PropertyItems":[{"Id":771,"Len":1,"Type":1,"Value":"00","$type":"PropertyItem"},{"Id":769,"Len":8,"Type":5,"Value":"A08601008FB10000","$type":"PropertyItem"},{"Id":20752,"Len":1,"Type":1,"Value":"01","$type":"PropertyItem"},{"Id":20753,"Len":4,"Type":4,"Value":"C30E0000","$type":"PropertyItem"},{"Id":20754,"Len":4,"Type":4,"Value":"C30E0000","$type":"PropertyItem"}],"$type":"Bitmap"},"AppName":"Android Notifier","PersistNotifications":false,"$type":"Message"}
2018-06-13 15:59:49.184 +10:00 [ERR] Encountered exception, quitting
System.ArgumentException: '.', hexadecimal value 0x00, is an invalid character.
   at System.Xml.XmlUtf8RawTextWriter.InvalidXmlChar(Int32 ch, Byte* pDst, Boolean entitize)
   at System.Xml.XmlUtf8RawTextWriter.WriteElementTextBlock(Char* pSrc, Char* pSrcEnd)
   at System.Xml.XmlUtf8RawTextWriter.WriteString(String text)
   at System.Xml.XmlWellFormedWriter.WriteString(String text)
   at NotificationsExtensions.XmlWriterHelper.Write(XmlWriter writer, Object element) in D:\Documents\GitHub\NotificationsExtensions\Windows 10\NotificationsExtensions\Common.cs:line 242
   at NotificationsExtensions.XmlWriterHelper.Write(XmlWriter writer, Object element) in D:\Documents\GitHub\NotificationsExtensions\Windows 10\NotificationsExtensions\Common.cs:line 228
   at NotificationsExtensions.XmlWriterHelper.Write(XmlWriter writer, Object element) in D:\Documents\GitHub\NotificationsExtensions\Windows 10\NotificationsExtensions\Common.cs:line 228
   at NotificationsExtensions.XmlWriterHelper.Write(XmlWriter writer, Object element) in D:\Documents\GitHub\NotificationsExtensions\Windows 10\NotificationsExtensions\Common.cs:line 234
   at NotificationsExtensions.BaseElement.GetContent() in D:\Documents\GitHub\NotificationsExtensions\Windows 10\NotificationsExtensions\Common.cs:line 391
   at GrowlToToast.Toaster.Program.ShowToast() in C:\Users\User1\Documents\GrowlToToast\src\Toaster\Program.cs:line 117
   at GrowlToToast.Toaster.Program.<>c.<Main>b__2_0(Options options) in C:\Users\User1\Documents\GrowlToToast\src\Toaster\Program.cs:line 45
2018-06-13 15:59:50.393 +10:00 [DBG] Received "{"Action":1,"Title":"Trent Pixel sent a ping","Body":"Test notification\u0000","Silent":false,"Image":"iVBORw0KGgoAAAANSUhEUgAAAEgAAABICAYAAABV7bNHAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAd9SURBVHhe7ZltUFRVGMftQ/mhPjVN2Uwz1dQHhppmasqSVCwVEFB53WXZN2CXXRZ2QWCB3WWX3UVaFMFcWVhgYRUEX8rIUZCUUilN8y2zlylrptK0fLnUZNqm4tNzLremxtuL7Lk1K/c/8x+Ge85zLs/v3POcey5TRIkSJUqUKFGiRIkSJUqUKFG3qja/deTBTUOHinsHDtb2bD0QsV4/eMi9aftBxY5jx+7kUgtfjT1vxNS1DZ62eLdCWWN/ZLupH+wtA7CsY2iksW/3PVyKE5dO1357iWfjPkPdRsipXgO59sg3yaOkoR9M9RtruTQnLkX5insVliCjda4DTU33LWNd7XpQWjuHuDQnrszChmkKSxejdQkLiIyf5+jG2Q1CXk0PCD0hBJC8qu0NLs2J6z8BhDCyjB6Q5RohR2cCidoIinKvoJAIIJUlQAtQkNG5eyHf2UPfrl5QlTVBdbUddu96E45/cAy29G8GfXElaBxr+WMouGDphsgApMXlZKpaCkcOH4Lr168D0aVLl6AriEvN0oJ91t0QQ8MRA4g8JfVNPjh37iwLh4iAGt65A/S21ewy44sL1xEFaKUvAKPMBQ7PuPbt2wtGhy8yACkRkL62D3RYqGlbiwWzqbkTmAvnOTTj2r//XSh2trI1ii8uXJP3OnVEPEEIaLm3A86d/Y5DM659e98BEwISnyAEUNfUDmdOf8OhGa9Bu3btAqOzXXyCNDXrwNnQBl9/9SWHB+DatWswuH07GGoCYpEmAGz1fvji8884PABXrlyBza+9DvqaTmznjwvXEQWosq4VPvn4Qw4PwM8/X4aevk2Q7wjyxtAwZUBdggIqq22F948e4fAAXLz4I7QHsT451vDG0HBEASpx+eG9A/s5PADfjzLg9a/BV4CIOWp0MflY+ck7C21r8KhR5PTD2yMjHB7ALf9bWOYNsKd7vhga1pPDKr3TfKdgp3nyaaPA0QbDw8O4vY+xgE6d/BrcK9ogFwHxxdAw5c8dnYwGH8s8PBbQNoGgs7fDtoFBdnsn+uLzE2Dz+CEH2/hiaDjf3RcpgNaCtrqD3davXr3CAvr4o+NgXtoaSYBaGbIUcu2YkADOswWgd/0rEAqFWECHDx1kz2E59m7e/jSsdSEgMy1AVS0MWQrkY7cgtnVBB27rP/10kQU0smcPGBx+UFev5e9PwRpnLwLyRwYgNXq5t5M9sJI69Fr/FtDaA+x1vv40TBdQpY8hg6pxpoWwyhaEsroADO/cCUePHIZ6bxCTCOJ1/v40TEpGtrmFDiB5hY9RYxIqa6cgVlo6QYNvzbbGXnCu6gNDbTdvP5omKyK73EcJkBkBWXGmLQFBTe5BZpevjbZJoZaWe2kAck5D0owKZ1lZ1SGs8Q8nTxP7k6+doknJkJZSAJSIgGRlzQwZVFHZJoyr2iG7wg/pBg+k6WpBWvIyXhPwfmjypEqXrKIASO2clmVczZBB5RWtAtgPWaWrQZJjgsrKKnC7XaAtMEKG3olteE8zX0z4VlkDkGFqogNIWrSKwS0Ri1oLfeO4cr0V+tZ1w5kzp2F0dJT99FFltYPUtIIFxBsXpsmKoAZIUvgyQwbFpUbd0iVesLmWwalTJ9mXRKKxsTEYHNgGyuI6yCoT5r5kRWQYG2gBWsnIynzsUqBtAsjT6IPzf/jHIdHInt2gMTdgIeWPC9dkaVMDtLiwniGDYlGjbgkCKnf72A9mv/wSwqfnGlw4fxaCPRtAZfZiO39cuMaXRNwUltMBtKjQw0hLMJnildSdiVaam8G9cg30bx2CHW/uhkDPq2B0toEEdzO+GBqW4YSnGDw0AJmnLTJ4GDJopqlRMMtwVjXWFtBV4w5T0Yzgmnj70XIW3i9F91L4gF7MKr4vJc81mmlqwjW7QjCnFzX8yXx9aJq8ay3SundwaU5cCQmmqXFKy3FCPb1w+U16GaQZbs7849B3prER4rLLV3FphqeZyboUhHQ5DRMmSf9bpxZ4bspphnqMIwnwj0fL5F7zJaUnno1XP8SlGL5i4pUz5qQamuekGTb8o1ML1r+QXjSQoLKNpehfwrVe948mf3SSuhowbojE845Lwzh27GK9a3qC/AEutf9H8zOMDycrHaEU3VJYnF/7tyaAFigt159P0li58FtfcbKyqCSFPYSFEBZqXH9pAiguu+TqjAXqIi50cig2zRiVKLeFFubVQHKu40bjdQJoXpbxckyCSsGFTR4RQAvklhCBkZRjv8EE0OxM0w/T47MXcyGTSwTQi/KKUKLaBgtU1j85MacaYtMKzz4zTzqX6z75FJumi3pBVh7C4gsJiqrfTX6fnZJ/8qk56c9yXSenCKBYaWkoXl6BRdgM8dkVEC+vhJlJmk+fiE19nOs2eTUjWRc1W1ISipOVw2+OSVQffSwm4RGuy+TWjGR11KwMfWh+VinMky6B5+Lk70TNir+faxbFAkrXheZmFsP0+bKh6Ofi7uaaRBGRJTZroQaenit5NTo69i7usqjf9HSs5PEnZ6W2PvpowlTukqg/Kjo68w78cdv4b6JEiRIl6uY1ZcqvkiXTI7HnmxIAAAAASUVORK5CYII=","AppName":"Android Notifier","PersistNotifications":false}"
2018-06-13 15:59:50.568 +10:00 [DBG] Deserialized {"Action":"Show","Title":"Trent Pixel sent a ping","Body":"Test notification\u0000","Silent":false,"Image":{"Tag":null,"PhysicalDimension":{"IsEmpty":false,"Width":72,"Height":72,"$type":"SizeF"},"Size":{"IsEmpty":false,"Width":72,"Height":72,"$type":"Size"},"Width":72,"Height":72,"HorizontalResolution":95.9866,"VerticalResolution":95.9866,"Flags":77842,"RawFormat":{"Guid":"b96b3caf-0728-11d3-9d7b-0000f81ef32e","$type":"ImageFormat"},"PixelFormat":"Format32bppArgb","Palette":{"Flags":1908806280,"Entries":[],"$type":"ColorPalette"},"FrameDimensionsList":["7462dc86-6180-4c7e-8e3f-ee7333a7a483"],"PropertyIdList":[771,769,20752,20753,20754],"PropertyItems":[{"Id":771,"Len":1,"Type":1,"Value":"00","$type":"PropertyItem"},{"Id":769,"Len":8,"Type":5,"Value":"A08601008FB10000","$type":"PropertyItem"},{"Id":20752,"Len":1,"Type":1,"Value":"01","$type":"PropertyItem"},{"Id":20753,"Len":4,"Type":4,"Value":"C30E0000","$type":"PropertyItem"},{"Id":20754,"Len":4,"Type":4,"Value":"C30E0000","$type":"PropertyItem"}],"$type":"Bitmap"},"AppName":"Android Notifier","PersistNotifications":false,"$type":"Message"}
```

**Comment by BobVul** [comment]
`"Body":"Test notification\u0000"`

Ok, there it is.

That is incredibly dodgy (it stinks of an off-by-one error somewhere in C code, probably in Growl or Android Notifier, because nulls terminate C strings), but I suppose I should be handling them just in case.

**Comment by BobVul** [comment]
@trentyarwood Try v2.0.2 https://github.com/BobVul/GrowlToToast/releases/tag/v2.0.2

Don't forget to turn off debug logging if it works. It tends to flood the logs.

**Comment by trentyarwood** [comment]
Success!

**Comment by BobVul** [comment]
\o/
