### ISSUE TITLE
Error running GrowlToToast

### ISSUE THREAD

**Issue by wout** [BobVul/GrowlToToast#25]
I'm getting the following error on launch. How can I get around this?

```
2019-07-01 09:53:01.063 +02:00 [ERR] Encountered exception, quitting
System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at GrowlToToast.Toaster.Program.GetMessage(Options options) in C:\Users\User1\Documents\GrowlToToast\src\Toaster\Program.cs:line 151
   at GrowlToToast.Toaster.Program.<>c.<Main>b__2_0(Options options) in C:\Users\User1\Documents\GrowlToToast\src\Toaster\Program.cs:line 47
2019-07-01 09:54:08.665 +02:00 [ERR] Encountered exception, quitting
System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at GrowlToToast.Toaster.Program.GetMessage(Options options) in C:\Users\User1\Documents\GrowlToToast\src\Toaster\Program.cs:line 151
   at GrowlToToast.Toaster.Program.<>c.<Main>b__2_0(Options options) in C:\Users\User1\Documents\GrowlToToast\src\Toaster\Program.cs:line 47
2019-07-01 09:55:23.171 +02:00 [ERR] Encountered exception, quitting
System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at GrowlToToast.Toaster.Program.GetMessage(Options options) in C:\Users\User1\Documents\GrowlToToast\src\Toaster\Program.cs:line 151
   at GrowlToToast.Toaster.Program.<>c.<Main>b__2_0(Options options) in C:\Users\User1\Documents\GrowlToToast\src\Toaster\Program.cs:line 47
```

**Comment by BobVul** [comment]
Can you go into Growl's plugin settings and tick "Enable debug logging"? It'll give me more info on the error. Once you've done that, try again and post the new log.

**Comment by BobVul** [comment]
![image](https://user-images.githubusercontent.com/1674237/60442959-86dc8000-9c5d-11e9-9fcd-b7f82b94a875.png)

**Comment by gimjun** [comment]
i was also having this error since updating to v1903 of Win10 - i didn't collect a log, but my workaround was placing shortcuts to both growl.exe and the growltotoast.exe in the startup folder (start+r, shell:startup) and checking "run as administrator" in both shortcuts' properties.
every time i start up my computer now it asks to confirm running as admin, but otherwise growl to toast seems to work fine

**Comment by BobVul** [comment]
Thanks for confirming the issue. I'll get an environment upgraded to 1903 and take a look.

**Comment by wout** [comment]
I just moved to Windows (from macOS then to Linux) and I feel I am missing something. Do I need to install something more than GrowlToToast? Every version of growl I find online is dated 2012 or before.

I'm on v1803 of Win 10.

**Comment by gimjun** [comment]
mate...  
'growltotoast' is a display for 'growl for windows', which integrates notifications into windows's native action centre system.  
first you need growl, then you need .net framework and another dependency, which you will be prompted for during growl install (and trying to launch it without them).  
then you can install 'growltotoast' following the developer bobvul's instructions.  
on win10 v1803 my growl setup was working flawlessly, so i do not understand how you are getting the above error. if you still cannot make it work, do as bob asks and send him the log of when you try to launch

**Comment by BobVul** [comment]
Right, so as gimjun mentioned, all this project implements is a display for [Growl for Windows](http://www.growlforwindows.com/). Unfortunately, GrowlToToast does not function as a standalone Growl client (server?).

You'll need to install Growl for Windows first, which provides a number of "display"s. A display is a way of showing a notification, and the built-in ones all appear as floating windows. Growl for Windows supports plugins that provide additional displays, which is what this is.

Once you have Growl for Windows installed, you can follow the [instructions in the readme](https://github.com/BobVul/GrowlToToast/blob/master/README.md#installation). You'll need to download the GrowlToToast installer, install that, and then run the GrowlerInstaller application to actually register the display with Growl for Windows (it does that by chucking the plugin dll into one of the Growl folders).

And because Growl for Windows is quite an old project, you'll need to install .NET 3.5 (available via Windows add/remove Features), though you should be prompted automatically for that. You should also have a .NET 4 (4.5/4.6/4.7), available by default on Windows 10. I need 4.x to actually show the toast.

**Comment by BobVul** [comment]
I'll also need to investigate why this isn't working on 1903. Seems like MS makes a habit of breaking this every other year :( (or... it could be the relatively hacky way this works? hm. I really should look at updating to the newer notification libs)

You should be fine on 1803 though, that's what the current release was most tested on.
